### ISSUE TITLE
Problem while using the punctuation example

### ISSUE THREAD

**Issue by Alienmaster** [plkmo/NLP_Toolkit#10]
Hi,
while using the example for punctuation i got a errormsg:
```
Traceback (most recent call last):
  File "punctuation.py", line 10, in <module>
    train_and_fit(config) # starts training with configured parameters
  File "/yyy/NLP_Toolkit/LSTM_env/lib/python3.6/site-packages/nlptoolkit/punctuation_restoration/trainer.py", line 28, in train_and_fit
    df, train_loader, train_length, max_features_length, max_output_len = load_dataloaders(args)
  File "/yyy/NLP_Toolkit/LSTM_env/lib/python3.6/site-packages/nlptoolkit/punctuation_restoration/preprocessing_funcs.py", line 315, in load_dataloaders
    df = create_TED_datasets(args)
  File "/yyy/NLP_Toolkit/LSTM_env/lib/python3.6/site-packages/nlptoolkit/punctuation_restoration/preprocessing_funcs.py", line 306, in create_TED_datasets
    df)
  File "/yyy/NLP_Toolkit/LSTM_env/lib/python3.6/site-packages/nlptoolkit/punctuation_restoration/preprocessing_funcs.py", line 34, in save_as_pickle
    with open(completeName, 'wb') as output:
FileNotFoundError: [Errno 2] No such file or directory: './data/eng.pkl'
```
The slightly changed sourcecode:
```
from nlptoolkit.utils.config import Config
from nlptoolkit.punctuation_restoration.trainer import train_and_fit
from nlptoolkit.punctuation_restoration.infer import infer_from_trained

config = Config(task='punctuation_restoration') # loads default argument parameters as above
config.data_path = "train.tags.en-fr.en" # sets training data path
config.batch_size = 32
config.lr = 5e-5 # change learning rate
config.model_no = 1 # sets model to PuncLSTM
train_and_fit(config) # starts training with configured parameters
inferer = infer_from_trained(config) # initiate infer object, which loads the model for inference, after training model
inferer.infer_from_input() # infer from user console input
# inferer.infer_from_file(in_file="./data/input.txt", out_file="./data/output.txt") # infer from input file
```

**Comment by Alienmaster** [comment]
creating the `data ` directory and moving the file into it fixes the problem. The `data ` path is hardcoded.
