### ISSUE TITLE
Punctuation Restoration. RuntimeError: shape '[32, 22, 2048]'

### ISSUE THREAD

**Issue by v-iashin** [plkmo/NLP_Toolkit#6]
Hi. Thanks for the implementation. I tried to train the punctuation restoration model with the default set of parameters but it failed with an error.

Here is the script:
```python
from nlptoolkit.utils.config import Config
from nlptoolkit.punctuation_restoration.trainer import train_and_fit
from nlptoolkit.punctuation_restoration.infer import infer_from_trained

config = Config(task='punctuation_restoration') # loads default argument parameters as above
config.data_path = "./data/train.tags.en-fr.en" # sets training data path
config.batch_size = 32
config.lr = 5e-5 # change learning rate
config.model_no = 1 # sets model to PuncLSTM
train_and_fit(config) # starts training with configured parameters
```

Traceback:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vladimir/repo1/punctuation_restoration/NLP_Toolkit/nlptoolkit/punctuation_restoration/trainer.py", line 94, in train_and_fit
    outputs, outputs2 = net(src_input, trg_input, trg2_input)
  File "/home/vladimir/miniconda3/envs/punc_restore/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/vladimir/repo1/punctuation_restoration/NLP_Toolkit/nlptoolkit/punctuation_restoration/models/LSTM_attention_model.py", line 314, in forward
    x = self.listener(x)
  File "/home/vladimir/miniconda3/envs/punc_restore/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/vladimir/repo1/punctuation_restoration/NLP_Toolkit/nlptoolkit/punctuation_restoration/models/LSTM_attention_model.py", line 34, in forward
    output, _ = self.layer2(output); #print("Listener output2:", output.shape)
  File "/home/vladimir/miniconda3/envs/punc_restore/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/vladimir/repo1/punctuation_restoration/NLP_Toolkit/nlptoolkit/punctuation_restoration/models/LSTM_attention_model.py", line 21, in forward
    x = x.contiguous().view(x.shape[0], int(x.shape[1]/2), 2*x.shape[2])
RuntimeError: shape '[32, 22, 2048]' is invalid for input of size 1474560
```

Dataset md5 hash
```
5d575762da3d9e628f0494b6ce8abeb9  ./data/train.tags.en-fr.en
```

Conda environment
```
name: punc_restore
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2020.1.1=0
  - certifi=2020.4.5.1=py36_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.3=he6710b0_1
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1g=h7b6447c_0
  - pip=20.0.2=py36_3
  - python=3.6.10=h7579374_2
  - readline=8.0=h7b6447c_0
  - setuptools=47.1.1=py36_0
  - sqlite=3.31.1=h62c20be_1
  - tk=8.6.8=hbc83047_0
  - wheel=0.34.2=py36_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - audioread==2.1.8
    - beautifulsoup4==4.9.1
    - blis==0.2.4
    - boto==2.49.0
    - boto3==1.9.238
    - botocore==1.12.253
    - cffi==1.14.0
    - chardet==3.0.4
    - click==7.1.2
    - cycler==0.10.0
    - cymem==2.0.3
    - dask==2.1.0
    - decorator==4.4.2
    - docutils==0.15.2
    - en-core-web-lg==2.1.0
    - fairseq==0.8.0
    - fastbpe==0.1.0
    - fasttext==0.9.1
    - filelock==3.0.12
    - h5py==2.10.0
    - idna==2.9
    - jieba==0.39
    - jmespath==0.10.0
    - joblib==0.15.1
    - kenlm==0.0.0
    - keras==2.3.1
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - kiwisolver==1.2.0
    - librosa==0.7.0
    - llvmlite==0.32.1
    - matplotlib==3.1.0
    - murmurhash==1.0.2
    - networkx==2.3
    - nltk==3.5
    - numba==0.49.1
    - numpy==1.16.4
    - pandas==0.24.2
    - pillow==7.1.2
    - plac==0.9.6
    - portalocker==1.7.0
    - preshed==2.0.1
    - pybind11==2.5.0
    - pycparser==2.20
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pytorch-nlp==0.4.1
    - pytz==2020.1
    - pyyaml==5.3.1
    - regex==2019.8.19
    - requests==2.23.0
    - resampy==0.2.2
    - s3transfer==0.2.1
    - sacrebleu==1.4.1
    - sacremoses==0.0.34
    - scikit-learn==0.21.2
    - scipy==1.4.1
    - sentencepiece==0.1.83
    - seqeval==0.0.12
    - six==1.12.0
    - soundfile==0.10.2
    - soupsieve==2.0.1
    - spacy==2.1.8
    - srsly==1.0.2
    - thinc==7.0.8
    - tokenizers==0.7.0
    - toolz==0.10.0
    - torch==1.4.0
    - torchtext==0.4.0
    - torchvision==0.5.0
    - tqdm==4.32.1
    - typing==3.7.4.1
    - urllib3==1.25.9
    - wasabi==0.6.0
```

Note:
The example in `README` has an unexpectable `'` in the line with `config.data_path = "./data/train.tags.en-fr.en"` which throws an error but it is not related to this issue.

**Comment by plkmo** [comment]
Please try again with the new update to set max_encoder_len & max_decoder_len to 80 in Config(task='punctuation_restoration') by default and let me know if the error still persists.

**Comment by v-iashin** [comment]
Everything seems to be working. Thanks!
